Add support for the Shapely extension
unikraft/lib-python3 pull request #17
Opened 2023-07-25 20:52 UTC by andreittr

This change set adds support for the shapely extension in the main Python build.

Depends on Python 3.10 and Numpy:
- https://github.com/unikraft/lib-python3/pull/15
- https://github.com/unikraft/lib-python3/pull/16
- https://github.com/unikraft/lib-python-numpy/pull/1

and all their dependencies. Contains all commits from https://github.com/unikraft/lib-python3/pull/16.
Commit c26d30d06e19ae76c2c98c18694ad70b85a6b142 adds shapely support. (Will rebase once numpy is mainlined)

The Shapely microlibrary is a separate PR:

2023-08-06 13:55 UTC, StefanJum requested changes
Looks good, but I think we should add the other library dependencies to the `Config.uk` file (maybe as `depends on` statements or something), like the `intel-intrinsis`, `libcxx*` etc.

2023-08-06 13:55 UTC, StefanJum commented on Config.uk
> +config LIBPYTHON3_EXTENSION_SHAPELY
Why not just select `LIBPYTHON_STAPELY` if the shapely extension is selected, or do a `depends on`?

2023-08-07 15:10 UTC, andreittr commented on Config.uk
> +config LIBPYTHON3_EXTENSION_SHAPELY
Same as for numpy, this is the pattern for extensions and shapely isn't special enough to break it.
As for using `depends on`, in Kconfig a block like
```
if CONDITION
   config ...
endif
```
is by definition equivalent to
```
config ...
depends on CONDITION
```
so they are functionally identical, but there is an argument to be made for style.

We could change the entire file around to use this format --- it might save a handful of lines --- but it's something that should be done in a python-wide PR.

2023-08-07 15:25 UTC, andreittr commented
> Looks good, but I think we should add the other library dependencies to the `Config.uk` file (maybe as `depends on` statements or something), like the `intel-intrinsis`, `libcxx*` etc.

I strongly disagree. `libcxx`, `intel-intrinsics`, etc. are not dependencies of python's bindings to shapely, but of shapely itself (actually, of shapely's dependencies) and should thus logically be expressed in the latter library --- and more generally I'm of the opinion that only direct dependencies should be expressed through Kconfig, with indirect depends and selects being pulled in as required.
That way we have one authoritative source of truth for dependencies, one that we can update in a single, well-defined location when they change.

2023-08-07 15:31 UTC, StefanJum commented
> I strongly disagree. `libcxx`, `intel-intrinsics`, etc. are not dependencies of python's bindings to shapely, but of shapely itself (actually, of shapely's dependencies) and should thus logically be expressed in the latter library --- and more generally I'm of the opinion that only direct dependencies should be expressed through Kconfig, with indirect depends and selects being pulled in as required. That way we have one authoritative source of truth for dependencies, one that we can update in a single, well-defined location when they change.

True. The final point is that everything should be eventually selected by some `Config.uk`. For example, is `intel-intrinsics` stated as a dependency by any library that ends up being selected when using python-shapely (I see that `lib-python-shapely` and `lib-geos` do not select it)?

2023-08-07 15:52 UTC, andreittr commented
> True. The final point is that everything should be eventually selected by some `Config.uk`. For example, is `intel-intrinsics` stated as a dependency by any library that ends up being selected when using python-shapely (I see that `lib-python-shapely` and `lib-geos` do not select it)?

`intel-intrinsics` is selected by numpy, since that lib is the only one that directly requires intrinsics (shapely does not directly use intrinsics in any way, nor does geos -- perfectly reflecting their Config.uk contents).
Same with C++: shapely does not directly use any C++, only numpy and geos do, and they indeed do select libcxx; if either drops C++ as a requirement in the future (numpy existed for many years without C++ so it's pefectly reasonable) it's clear where this change needs to be reflected.

2023-08-07 15:54 UTC, StefanJum commented
> `intel-intrinsics` is selected by numpy, since that lib is the only one that directly requires intrinsics (shapely does not directly use intrinsics in any way, nor does geos -- perfectly reflecting their Config.uk contents). Same with C++: shapely does not directly use any C++, only numpy and geos do, and they indeed do select libcxx; if either drops C++ as a requirement in the future (numpy existed for many years without C++ so it's pefectly reasonable) it's clear where this change needs to be reflected.

Perfect, then it's all good.

2023-08-07 15:54 UTC, StefanJum commented on Config.uk
> +config LIBPYTHON3_EXTENSION_SHAPELY
> We could change the entire file around to use this format --- it might save a handful of lines --- but it's something that should be done in a python-wide PR.

Agree, let's leave it like it is now.

2023-08-10 18:21 UTC, StefanJum approved these changes
All good @andreittr, I'll add the tag after all `numpy` and `libgeos` dependencies are merged.

2023-08-11 16:03 UTC, StefanJum commented
@andreittr you can rebase this now, https://github.com/unikraft/lib-python3/pull/15 is merged :tada:

2023-08-11 17:09 UTC, andreittr commented
> @andreittr you can rebase this now, #15 is merged tada

Will rebase it directly onto numpy once it gets merged.
- https://github.com/unikraft/lib-python3/pull/16

2023-08-14 13:17 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-14 13:18 UTC, mariasfiraiala approved these changes
All good with me now, good job!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-08-14 19:13 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-14 19:23 UTC, closed without merging